name: Deploy Branch to Netlify

on:
  pull_request:

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Packages
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: build/web
          production-branch: ${{ github.head_ref }} + "-" + ${{ github.sha }}
          deploy-message: 'GH-ACTIONS: Deploy of PR from ${{ github.head_ref }}'
          enable-commit-status: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-deploy: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
