name: Test PR

on:
  pull_request:
  push:
    branches:
      - flutter

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Packages
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run Tests
        run: flutter test

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Build App Bundle
        run: flutter build appbundle

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Packages
        run: flutter pub get

      - name: Build Web
        run: flutter build web
