name: Release Pipeline

on:
  release:
    types:
      - published

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Generate build number
        run: echo "SENTRY_RELEASE=${{ github.sha }}" >> $GITHUB_ENV

      - name: Write info.json
        run: |
          sudo apt-get install -y jq
          COMMIT_SHA=$(git rev-parse --short HEAD)
          jq --arg sha "$SENTRY_RELEASE" '.sha = $sha' static/info.json > temp.json && mv temp.json static/info.json
          jq --arg date "$(date -Iseconds)" '.build_date = $date' static/info.json > temp.json && mv temp.json static/info.json
          jq --arg version "${{ github.event.release.tag_name }}" '.version = $version' static/info.json > temp.json && mv temp.json static/info.json

      - name: Build Svelte app
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-artifacts
          path: .vercel/

  # upload-artifacts:
  #   name: Upload Artifacts to Release
  #   needs: build-android
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download Artifact
  #       uses: actions/download-artifact@v3

  #     - name: Upload APK to Release
  #       uses: actions/upload-release-asset@v1
  #       with:
  #         upload_url: ${{ github.event.release.upload_url }}
  #         asset_path: signed-apk/vertretungsapp-release.apk
  #         asset_name: vertretungsapp-release.apk
  #         asset_content_type: application/vnd.android.package-archive
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-vercel:
    name: Deploy to Vercel
    needs: build-web
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-artifacts
          path: .vercel/

      - name: Deploy to Vercel (Staging)
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.RELEASEPLEASE_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
          PRODUCTION: ${{ !github.event.release.prerelease }}
          ALIAS_DOMAINS: |
            staging-vertretungsapp.vercel.app
            {SHA}.staging-vertretungsapp.vercel.app
            staging.vertretungsapp.de
            ${{ !github.event.release.prerelease }}:
              app.vertretungsapp.de
